version: '3.8'

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notebook_app
    hostname: notebook_app
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    networks:
      - app_network
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    hostname: database
    environment:
      POSTGRES_USER: notebook_app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notebook_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notebook_app_user -d notebook_app"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
